# COMMON PROPERTIES TO ALL PROFILES
spring.config.activate.on-profile=dev,cert,prod
spring.application.name=FullRestApp
server.servlet.context-path=/rest-demo-app
management.endpoints.web.exposure.include=*
#spring.jackson.default-property-inclusion=NON_NULL
springfox.documentation.swagger-ui.enabled=true
spring.jpa.show-sql=false