logging.file.path=C:/Reply/corso Tech4Tech/logging/test

# POSTGRES DB CONFIGURATIONS
spring.datasource.url=jdbc:postgresql://89.168.72.242:5432/workshop_sb
spring.datasource.username=postgres
spring.datasource.password=Technology.01
## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5
# create and drop table, good for testing, production set to none or comment it
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.show-sql=true
rest.log.pretty.print=false
